### ISSUE TITLE
Insert/Update don´t know what Id uses

### ISSUE THREAD

**Issue by antoniovendramin** [StackExchange/dapper-dot-net#481]
Hi, I´m using the Dapper.Contrib to Insert and Update my data on the database, but
the Dapper.Contrib does not know how to use the Id, because on the insert it requeres an "**id**" and 
on the Update, it requires "**Id**".
Insert   = Message: 42703: column "**id**" does not exist
Update = Message: 42703: column "**Id**" does not exist

I´m using the Dapper.Contrib (1.50.0-beta8)

Thanks

**Comment by xmedeko** [comment]
Do you have a property annotated by the `[Key]` attribute?

**Comment by antoniovendramin** [comment]
No, I clone the Dapper.Contrib and ToLower the properties name.
For me fixed. I don´t know if this is a good idea to suggest.

**Comment by NickCraver** [comment]
Closing to cleanup, this is under review on many other issues in v2.

**Comment by timematcher** [comment]
Is this issue solved in the latest Dapper.Contrib on nuget? I am using 1.50.2 and facing the exact same problem.

I am using Postgresql as backend database and its column are case insensitive. I am making a call to 
`InsertAsync<Session>(sessionObj);`

Dapper.Contrib tries to look for Session_Guid and fails to find it. Session_guid exists in the database.

The problem is, Dapper.Contrib is enclosing each column names in quotes which is being rejected by the database. The query being generated is this:
`INSERT INTO Session ("Session_Guid", "AU_Guid", "AU_Id", "Valid_Till", "Created", "Last_Modified", "Is_Enabled") VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING Auth_Id`

When this query is manually run against postgresql database, it errors out.
**ERROR: column "AU_Guid" of relation "session" does not exist
SQL state: 42703
Character: 36**

**Is there a way to prevent Dapper/Dapper.Contrib from quoting the columns?**

**Comment by mikegottlieb** [comment]
This is still a problem as far as I can tell and it is driving me crazy

**Comment by Alikhll** [comment]
same error for me on PostgreSQL
`Npgsql.PostgresException: '42703: column "id" does not exist'`
I tried Key annotation and raises same error
but work using ExplicitKey which I expected not to generate Id in database but database generate id automatically!

**Comment by mikegottlieb** [comment]
I ended up switching to NPoco, which seems to support Postgres a bit better. Plus it contains some of useful things that are only found in Dapper extensions which tend to have even less support for Postgres. I still recommend Dapper to people, but usually only when they are using SQL Server.

**Comment by Huhra** [comment]
I had the same error, using pgsql it seems fields have to be lowercase, now working

**Comment by dogac00** [comment]
I am having the same problem, Error is: "column "id" does not exist", anyone have a solution for this?

**Comment by dogac00** [comment]
Guys I found the solution, add ExplicitKey attribute on your Id. 😁

**Comment by dani-fmena** [comment]
@dogac00, Where you able to solve the problem ? ...

**Comment by dogac00** [comment]
@dani-fmena No, this problem can only be solved by updating your column name as `id` in your table. If you are not using a different column for primary key and annotating that property of course. So if you are using `"Id"`, this will give an error. So, my recommendation is always follow Postgres convention and use `snake_case` when naming columns.
